/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_attendance_control_system;

import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author acer
 */
public class Marks_Allocation extends javax.swing.JFrame {

    /**
     * Creates new form Marks_Allocation
     */
    public Marks_Allocation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mark_date = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mark_subject = new javax.swing.JTextField();
        mark_stuid = new javax.swing.JTextField();
        mark_teacherId = new javax.swing.JTextField();
        mark_papernu = new javax.swing.JComboBox<>();
        marks_obtain = new javax.swing.JTextField();
        marks_outOf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        stuid_search = new javax.swing.JTextField();
        marks_search_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        marks_add = new javax.swing.JButton();
        mark_update = new javax.swing.JButton();
        mark_delete = new javax.swing.JButton();
        mark_reset = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Manage Marks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Date");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Subject");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Student Id");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Teacher Id");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("paper number");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Marks obtain");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Marks outof");

        mark_papernu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mark_teacherId)
                            .addComponent(mark_stuid)
                            .addComponent(mark_subject)
                            .addComponent(mark_date, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mark_papernu, 0, 151, Short.MAX_VALUE)
                            .addComponent(marks_obtain)
                            .addComponent(marks_outOf))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(mark_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mark_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mark_stuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mark_teacherId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mark_papernu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(marks_obtain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(marks_outOf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Manage Marks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Student Id");

        marks_search_btn.setBackground(new java.awt.Color(255, 255, 255));
        marks_search_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        marks_search_btn.setForeground(new java.awt.Color(0, 0, 102));
        marks_search_btn.setText("Search");
        marks_search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks_search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(stuid_search, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(marks_search_btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(stuid_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(marks_search_btn)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Marks Allocation");

        marks_add.setBackground(new java.awt.Color(255, 255, 255));
        marks_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        marks_add.setForeground(new java.awt.Color(0, 0, 102));
        marks_add.setText("Add");
        marks_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks_addActionPerformed(evt);
            }
        });

        mark_update.setBackground(new java.awt.Color(255, 255, 255));
        mark_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mark_update.setForeground(new java.awt.Color(0, 0, 102));
        mark_update.setText("Update");
        mark_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark_updateActionPerformed(evt);
            }
        });

        mark_delete.setBackground(new java.awt.Color(255, 255, 255));
        mark_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mark_delete.setForeground(new java.awt.Color(0, 0, 102));
        mark_delete.setText("Delete");
        mark_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark_deleteActionPerformed(evt);
            }
        });

        mark_reset.setBackground(new java.awt.Color(255, 255, 255));
        mark_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mark_reset.setForeground(new java.awt.Color(0, 0, 102));
        mark_reset.setText("Reset");
        mark_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(marks_add)
                .addGap(18, 18, 18)
                .addComponent(mark_update)
                .addGap(18, 18, 18)
                .addComponent(mark_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mark_reset)
                .addGap(60, 60, 60))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marks_add)
                    .addComponent(mark_update)
                    .addComponent(mark_delete)
                    .addComponent(mark_reset))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marks_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks_addActionPerformed
       SimpleDateFormat date = new SimpleDateFormat("YYYY-MM-dd");
       String Date=date.format(mark_date.getDate());
       
        String marksub=mark_subject.getText();
        String mstuid=mark_stuid.getText();
        String mteacherid=mark_teacherId.getText();
        String paperno=mark_papernu.getSelectedItem().toString();
        String markobtain=marks_obtain.getText();
        String markoutof=marks_outOf.getText();

        ConnectionDB c=new ConnectionDB();
        try{
            
            Statement stmt=c.getConnectionDB().createStatement();
            
            String query="insert into mark(MDate,MSubject,MStuId,MTeacherId,MPaperNo,markOutOf,MarkObtain) values('"+Date+"','"+marksub+"','"+mstuid+"','"+mteacherid+"','"+paperno+"','"+markoutof+"','"+markobtain+"')";

            int n=stmt.executeUpdate(query);
            if(n!=0){
                JOptionPane.showMessageDialog(rootPane,"Recorded Successfully Added");

            }
            else{
                JOptionPane.showMessageDialog(rootPane,"Not Successfully Added");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_marks_addActionPerformed

    private void mark_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark_updateActionPerformed
         String marksub=mark_subject.getText();
        String mstuid=mark_stuid.getText();
        String mteacherid=mark_teacherId.getText();
        String paperno=mark_papernu.getSelectedItem().toString();
        String markobtain=marks_obtain.getText();
        String markoutof=marks_outOf.getText();

        String mmstuid = stuid_search.getText();
        
        SimpleDateFormat date = new SimpleDateFormat("YYYY-MM-dd");
        String Date=date.format(mark_date.getDate());

        ConnectionDB c=new ConnectionDB();
        try{
            
            Statement stmt=c.getConnectionDB().createStatement();
           
            String query="update mark set MDate='"+Date+"',MSubject='"+marksub+"',MStuId='"+mstuid+"',MTeacherId='"+mteacherid+"',MPaperNo='"+paperno+"',markOutOf='"+markoutof+"',MarkObtain='"+markobtain+"' where MStuId='"+mmstuid+"' ";

            
            int n=stmt.executeUpdate(query);
            if(n!=0){
                JOptionPane.showMessageDialog(rootPane,"Updated Successfully");

            }
            else{
                JOptionPane.showMessageDialog(rootPane,"Update Wrong");
            }
            stmt.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
      
        
    }//GEN-LAST:event_mark_updateActionPerformed

    private void marks_search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks_search_btnActionPerformed
          
        String mmstuid = stuid_search.getText();

        ConnectionDB c=new ConnectionDB();
        try{
            
            Statement stmt=c.getConnectionDB().createStatement();
            
            String query="select * from mark where MStuId='"+mmstuid+"'";
            
            ResultSet rs=stmt.executeQuery(query);
            rs.next();

            mark_subject.setText(rs.getString("MSubject"));
            mark_stuid.setText(rs.getString("MStuId"));
            mark_teacherId.setText(rs.getString("MTeacherId"));
            mark_papernu.setSelectedItem(rs.getString("MPaperNo"));
            marks_obtain.setText(rs.getString("MarkObtain"));
            marks_outOf.setText(rs.getString("markOutOf"));
            Date date = new SimpleDateFormat("YYYY-MM-dd").parse((String)(rs.getString("Mdate")));
            mark_date.setDate(date);

            rs.close();
            stmt.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_marks_search_btnActionPerformed

    private void mark_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark_deleteActionPerformed
         String mmstuid = stuid_search.getText();

        ConnectionDB c=new ConnectionDB();

        try{
            
            Statement stmt=c.getConnectionDB().createStatement();
            
            String query="Delete from mark where MStuId='"+mmstuid+"'";
          
            int opt=JOptionPane.showConfirmDialog(rootPane,"Are you sure you want to delete this record?");
            System.out.println(opt);
            if(opt == 0){
                int n=stmt.executeUpdate(query);
                if(n!=0){
                    JOptionPane.showMessageDialog(rootPane,"Deleted Successfully");

                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"Error while deleting the record");

                }
            }
            else if(opt == 2){

                mark_date.setDate(null);

                stuid_search.setText("");
                mark_subject.setText("");
                mark_stuid.setText("");
                mark_teacherId.setText("");
                mark_papernu.setSelectedIndex(0);
                marks_obtain.setText("");
                marks_outOf.setText("");

                stmt.close();

            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_mark_deleteActionPerformed

    private void mark_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark_resetActionPerformed
         mark_date.setDate(null);

                stuid_search.setText("");
                mark_subject.setText("");
                mark_stuid.setText("");
                mark_teacherId.setText("");
                mark_papernu.setSelectedIndex(0);
                marks_obtain.setText("");
                marks_outOf.setText("");
    }//GEN-LAST:event_mark_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marks_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marks_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marks_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marks_Allocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marks_Allocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField4;
    private com.toedter.calendar.JDateChooser mark_date;
    private javax.swing.JButton mark_delete;
    private javax.swing.JComboBox<String> mark_papernu;
    private javax.swing.JButton mark_reset;
    private javax.swing.JTextField mark_stuid;
    private javax.swing.JTextField mark_subject;
    private javax.swing.JTextField mark_teacherId;
    private javax.swing.JButton mark_update;
    private javax.swing.JButton marks_add;
    private javax.swing.JTextField marks_obtain;
    private javax.swing.JTextField marks_outOf;
    private javax.swing.JButton marks_search_btn;
    private javax.swing.JTextField stuid_search;
    // End of variables declaration//GEN-END:variables
}
