/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_attendance_control_system;

/**
 *
 * @author acer
 */
public class Staff extends javax.swing.JFrame {

    /**
     * Creates new form Staff
     */
    public Staff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Sending_Notifi_Label = new javax.swing.JLabel();
        Marks_Allo_Label = new javax.swing.JLabel();
        Report_Gene_Label = new javax.swing.JLabel();
        Student_mgt_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Operation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jPanel1ComponentRemoved(evt);
            }
        });

        Sending_Notifi_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sending_Notifi_Label.setForeground(new java.awt.Color(0, 0, 102));
        Sending_Notifi_Label.setText("Sending Notification");
        Sending_Notifi_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sending_Notifi_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sending_Notifi_LabelMouseClicked(evt);
            }
        });

        Marks_Allo_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Marks_Allo_Label.setForeground(new java.awt.Color(0, 0, 102));
        Marks_Allo_Label.setText("Marks Allocation");
        Marks_Allo_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Marks_Allo_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Marks_Allo_LabelMouseClicked(evt);
            }
        });

        Report_Gene_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Report_Gene_Label.setForeground(new java.awt.Color(0, 0, 102));
        Report_Gene_Label.setText("Report Generating");
        Report_Gene_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Report_Gene_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Report_Gene_LabelMouseClicked(evt);
            }
        });

        Student_mgt_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Student_mgt_Label.setForeground(new java.awt.Color(0, 0, 102));
        Student_mgt_Label.setText("Student Managment");
        Student_mgt_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Student_mgt_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Student_mgt_LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sending_Notifi_Label)
                    .addComponent(Student_mgt_Label)
                    .addComponent(Report_Gene_Label)
                    .addComponent(Marks_Allo_Label))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Sending_Notifi_Label)
                .addGap(18, 18, 18)
                .addComponent(Marks_Allo_Label)
                .addGap(18, 18, 18)
                .addComponent(Report_Gene_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Student_mgt_Label)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Hello !!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sending_Notifi_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sending_Notifi_LabelMouseClicked
       Sending_Notification obj1=new Sending_Notification();
       obj1.setVisible(true);
    }//GEN-LAST:event_Sending_Notifi_LabelMouseClicked

    private void Marks_Allo_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Marks_Allo_LabelMouseClicked
       Marks_Allocation obj2=new Marks_Allocation();
       obj2.setVisible(true);
    }//GEN-LAST:event_Marks_Allo_LabelMouseClicked

    private void Report_Gene_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Report_Gene_LabelMouseClicked
        Report_Generating obj3= new Report_Generating();
        obj3.setVisible(true);
    }//GEN-LAST:event_Report_Gene_LabelMouseClicked

    private void Student_mgt_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Student_mgt_LabelMouseClicked
        StudentManagment obj4=new StudentManagment();
        obj4.setVisible(true);
    }//GEN-LAST:event_Student_mgt_LabelMouseClicked

    private void jPanel1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Marks_Allo_Label;
    private javax.swing.JLabel Report_Gene_Label;
    private javax.swing.JLabel Sending_Notifi_Label;
    private javax.swing.JLabel Student_mgt_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
