/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_attendance_control_system;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author acer
 */
public class StudentManagment extends javax.swing.JFrame {

   PreparedStatement pst=null;
    public StudentManagment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Stu_search_Id = new javax.swing.JTextField();
        Student_search_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        stu_image = new javax.swing.JLabel();
        img_chooser_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Stu_fname = new javax.swing.JTextField();
        Stu_Lname = new javax.swing.JTextField();
        Stu_Nic = new javax.swing.JTextField();
        Stu_DOB = new com.toedter.calendar.JDateChooser();
        rbt_Male = new javax.swing.JRadioButton();
        rbt_Female = new javax.swing.JRadioButton();
        Std_phone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Std_Address = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        Std_id = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Pre_fname = new javax.swing.JTextField();
        Pre_Lname = new javax.swing.JTextField();
        Pre_nic = new javax.swing.JTextField();
        Pre_phone = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Pre_id = new javax.swing.JTextField();
        rbt_pre_male = new javax.swing.JRadioButton();
        rbt_pre_Female = new javax.swing.JRadioButton();
        Add_Student_btn = new javax.swing.JButton();
        Update_student_btn = new javax.swing.JButton();
        Delete_student_btn = new javax.swing.JButton();
        Student_reset_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Student Managment");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Student Id");

        Student_search_btn.setBackground(new java.awt.Color(255, 255, 255));
        Student_search_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Student_search_btn.setForeground(new java.awt.Color(0, 0, 102));
        Student_search_btn.setText("Search");
        Student_search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_search_btnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Student Details"));

        jDesktopPane1.setLayer(stu_image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stu_image, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stu_image, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        img_chooser_btn.setBackground(new java.awt.Color(255, 255, 255));
        img_chooser_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        img_chooser_btn.setForeground(new java.awt.Color(0, 0, 102));
        img_chooser_btn.setText("Choose");
        img_chooser_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                img_chooser_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(img_chooser_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(img_chooser_btn)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Student Information"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("First name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Last name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("NIC");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Date of Birth");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Phone No");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Address");

        buttonGroup1.add(rbt_Male);
        rbt_Male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbt_Male.setForeground(new java.awt.Color(0, 0, 102));
        rbt_Male.setText("Male");

        buttonGroup1.add(rbt_Female);
        rbt_Female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbt_Female.setForeground(new java.awt.Color(0, 0, 102));
        rbt_Female.setText("Female");

        Std_Address.setColumns(20);
        Std_Address.setRows(5);
        jScrollPane1.setViewportView(Std_Address);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Student Id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbt_Male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbt_Female))
                    .addComponent(Stu_fname)
                    .addComponent(Stu_Lname)
                    .addComponent(Stu_Nic)
                    .addComponent(Stu_DOB, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(Std_phone)
                    .addComponent(Std_id))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Stu_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Stu_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Stu_Nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(Stu_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbt_Male)
                        .addComponent(rbt_Female)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(Std_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Std_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Parent Information"));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("First name");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Last name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("NIC");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Gender");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Phone No");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("parent Id");

        buttonGroup2.add(rbt_pre_male);
        rbt_pre_male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbt_pre_male.setForeground(new java.awt.Color(0, 0, 102));
        rbt_pre_male.setText("Male");

        buttonGroup2.add(rbt_pre_Female);
        rbt_pre_Female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbt_pre_Female.setForeground(new java.awt.Color(0, 0, 102));
        rbt_pre_Female.setText("Female");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pre_phone)
                    .addComponent(Pre_id)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Pre_fname)
                                .addComponent(Pre_Lname)
                                .addComponent(Pre_nic, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbt_pre_male, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbt_pre_Female)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Pre_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Pre_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Pre_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rbt_pre_male)
                    .addComponent(rbt_pre_Female))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Pre_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Pre_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        Add_Student_btn.setBackground(new java.awt.Color(255, 255, 255));
        Add_Student_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add_Student_btn.setForeground(new java.awt.Color(0, 0, 102));
        Add_Student_btn.setText("Add");
        Add_Student_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Student_btnActionPerformed(evt);
            }
        });

        Update_student_btn.setBackground(new java.awt.Color(255, 255, 255));
        Update_student_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update_student_btn.setForeground(new java.awt.Color(0, 0, 102));
        Update_student_btn.setText("Update");
        Update_student_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_student_btnActionPerformed(evt);
            }
        });

        Delete_student_btn.setBackground(new java.awt.Color(255, 255, 255));
        Delete_student_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete_student_btn.setForeground(new java.awt.Color(0, 0, 102));
        Delete_student_btn.setText("Delete");
        Delete_student_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_student_btnActionPerformed(evt);
            }
        });

        Student_reset_btn.setBackground(new java.awt.Color(255, 255, 255));
        Student_reset_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Student_reset_btn.setForeground(new java.awt.Color(0, 0, 102));
        Student_reset_btn.setText("Reset");
        Student_reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_reset_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Stu_search_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Student_search_btn)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add_Student_btn)
                .addGap(38, 38, 38)
                .addComponent(Update_student_btn)
                .addGap(43, 43, 43)
                .addComponent(Delete_student_btn)
                .addGap(39, 39, 39)
                .addComponent(Student_reset_btn)
                .addGap(200, 200, 200))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Student_btn)
                    .addComponent(Update_student_btn)
                    .addComponent(Delete_student_btn)
                    .addComponent(Student_reset_btn))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(Stu_search_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Student_search_btn))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void img_chooser_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_img_chooser_btnActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        
        try{
            File image1 = new File(filename);
            ImageIcon image2= new ImageIcon(filename);
            stu_image.setIcon(image2);
            
            FileInputStream FIS = new FileInputStream(image1);
            ByteArrayOutputStream BOS=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readNum;(readNum=FIS.read(buf))!=-1;){
            BOS.write(buf,0,readNum);
            }
            
            student_img=BOS.toByteArray();
            System.out.println(student_img);
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_img_chooser_btnActionPerformed

    private void Add_Student_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Student_btnActionPerformed
       try{
            ConnectionDB conn=new ConnectionDB();
            String query1="insert into student_parent(SID,SFName,SLName,SNIC,SAddress,SPhoneNumber,SGender,SPhoto,SDOB,ParentID,PFName,PLName,PNIC,PPhone,PGender) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            
            String Student_fname=Stu_fname.getText();
            String Student_Lname=Stu_Lname.getText();
            String student_NIC=Stu_Nic.getText();
            SimpleDateFormat date = new SimpleDateFormat("YYYY-MM-dd");
            String Date=date.format(Stu_DOB.getDate());
            String Stu_gender=rbt_Male.isSelected()?"Male":"Female";
            String Student_phone=Std_phone.getText();
            String address=Std_Address.getText();
            String Student_id=Std_id.getText();
            
            /*String Subject="";
            if(Accouting.isSelected()){
              Subject+=Accouting.getText()+" ";
            }
            if(BusinessStu.isSelected()){
              Subject+=BusinessStu.getText()+" ";
            }
             if(Economics.isSelected()){
              Subject+=Economics.getText()+" ";
            }*/
            
            
            
            
            
        String parentid=Pre_id.getText();
        String parentfname=Pre_fname.getText();
        String parentlname=Pre_Lname.getText();
        String parentphone=Pre_phone.getText();
        String parentnic=Pre_nic.getText();
        
        String Pre_gender=rbt_pre_male.isSelected()?"Male":"Female";
        
        
            
            
             pst=conn.getConnectionDB().prepareStatement(query1);
            
            pst.setString(1, Student_id);
            pst.setString(2, Student_fname);
            pst.setString(3, Student_Lname);
            pst.setString(4, student_NIC);
            pst.setString(5, address);
            pst.setString(6, Student_phone);
            pst.setString(7, Stu_gender);
            pst.setBytes(8, student_img);
            pst.setString(9, Date);
            pst.setString(10, parentid);
            pst.setString(11, parentfname);
            pst.setString(12, parentlname);
            pst.setString(13, parentnic);
            pst.setString(14,parentphone );
            pst.setString(15, Pre_gender);
           
           
            
            pst.execute();
            JOptionPane.showMessageDialog(this, "Insert Successfully");
        
        
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_Add_Student_btnActionPerformed

    private void Update_student_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_student_btnActionPerformed
       String id=Std_id.getText();
        String fname=Stu_fname.getText();
        String lname=Stu_Lname.getText();
        String nic=Stu_Nic.getText();
        String gender=rbt_Male.isSelected()?"Male":"Female";
        SimpleDateFormat date = new SimpleDateFormat("YYYY-MM-dd");
        String Date=date.format(Stu_DOB.getDate());
        /*String Subject="";
            if(Accouting.isSelected()){
              Subject+=Accouting.getText()+" ";
            }
            if(BusinessStu.isSelected()){
              Subject+=BusinessStu.getText()+" ";
            }
             if(Economics.isSelected()){
              Subject+=Economics.getText()+" ";
            }*/
            
        
        String address=Std_Address.getText();
        String phone=Std_phone.getText();
        String parentid=Pre_id.getText();
        String parentfname=Pre_fname.getText();
        String parentlname=Pre_Lname.getText();
        String parentphone=Pre_phone.getText();
        String parentnic=Pre_nic.getText();
        String gender1=rbt_pre_male.isSelected()?"Male":"Female";
        

        ConnectionDB c=new ConnectionDB();

        try {
            
            Statement stmt=c.getConnectionDB().createStatement();
           
            String query="update student_parent set SID='"+id+"',SFName='"+fname+"',SLName='"+lname+"',SNIC='"+nic+"',SAddress='"+address+"',SPhoneNumber='"+phone+"',SGender='"+gender+"',ParentID='"+parentid+"',PFName='"+parentfname+"',PLName='"+parentlname+"',PNIC='"+parentnic+"',PPhone='"+parentphone+"',PGender='"+gender1+"' where SID='"+id+"'";
            
           
            int n=stmt.executeUpdate(query);
            
            if(n!=0){
                JOptionPane.showMessageDialog(rootPane,"Update successfully");
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"Update Wrong");
            }
            stmt.close();
            // con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_Update_student_btnActionPerformed

    private void Student_search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_search_btnActionPerformed
        String id=Stu_search_Id.getText();

        ConnectionDB c=new ConnectionDB();

        try {
            
            Statement stmt=c.getConnectionDB().createStatement();
           
            String query="select* from student_parent Where SID='"+id+"'";
            

            ResultSet rs=stmt.executeQuery(query);
            if(rs.next()){

            Std_id.setText(rs.getString("SID"));
            Stu_fname.setText(rs.getString("SFName"));
            Stu_Lname.setText(rs.getString("SLName"));
            Stu_Nic.setText(rs.getString("SNIC"));
            Std_Address.setText(rs.getString("SAddress"));
            Std_phone.setText(rs.getString("SPhoneNumber"));
            Date date = new SimpleDateFormat("YYYY-MM-dd").parse((String)(rs.getString("SDOB")));
            Stu_DOB.setDate(date);
            
           // String Subject= rs.getString("Sub_name");
            
            
            
            
           
            
            
            byte[]imagedata=rs.getBytes("SPhoto");
            format = new ImageIcon(imagedata);
            stu_image.setIcon(format);

            Pre_id.setText(rs.getString("ParentId"));
           
            Pre_fname.setText(rs.getString("PFName"));
            Pre_Lname.setText(rs.getString("PLName"));
            Pre_nic.setText(rs.getString("PNIC"));
            Pre_phone.setText(rs.getString("PPhone"));

            if(rs.getString("PGender").equals("Male"))
            {
                rbt_pre_Female.setSelected(false);
               
                rbt_pre_male.setSelected(true);
                
            }
            else
            {
                rbt_pre_Female.setSelected(true);
               
                rbt_pre_male.setSelected(false);
            }

            if(rs.getString("SGender").equals("Male"))
            {
                rbt_Female.setSelected(false);
                
                rbt_Male.setSelected(true);
                
            }
            else
            {
              rbt_Female.setSelected(true);
                
                rbt_Male.setSelected(false); 
            }
            }
           

            rs.close();
            stmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_Student_search_btnActionPerformed

    private void Delete_student_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_student_btnActionPerformed

         String id=Stu_search_Id.getText();

        ConnectionDB c=new ConnectionDB();

        try {
            
            Statement stmt=c.getConnectionDB().createStatement();
            
            String query="delete from student_parent where SID='"+id+"' ";
           
            int opt=JOptionPane.showConfirmDialog(rootPane,"Are you sure you want to delete this record?");

            if(opt==0){
                int n=stmt.executeUpdate(query);

                if(n!=0){
                    JOptionPane.showMessageDialog(rootPane,"Delete successfully");
                    
                Stu_fname.setText(" ");
                Stu_Lname.setText(" ");
                Stu_Nic.setText(" ");
                buttonGroup1.clearSelection();
               
                Std_Address.setText(" ");
                Std_phone.setText(" ");
                Std_id.setText("");
            
            Stu_DOB.setDate(null);
            
            stu_image.setIcon(null);
            
            

            Pre_id.setText("");
           
            Pre_fname.setText("");
            Pre_Lname.setText("");
            Pre_nic.setText("");
            Pre_phone.setText("");
                    
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"Error while deleting records");
                }
            }

            else if(opt ==2){

                Stu_fname.setText(" ");
                Stu_Lname.setText(" ");
                Stu_Nic.setText(" ");
                buttonGroup1.clearSelection();
               
                Std_Address.setText(" ");
                Std_phone.setText(" ");
                Std_id.setText("");
            
            Stu_DOB.setDate(null);
            
            stu_image.setIcon(null);

            Pre_id.setText("");
           
            Pre_fname.setText("");
            Pre_Lname.setText("");
            Pre_nic.setText("");
            Pre_phone.setText("");

            }

            stmt.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_Delete_student_btnActionPerformed

    private void Student_reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_reset_btnActionPerformed
        Stu_fname.setText(" ");
                Stu_Lname.setText(" ");
                Stu_Nic.setText(" ");
                buttonGroup1.clearSelection();
               buttonGroup2.clearSelection();
                Std_Address.setText(" ");
                Std_phone.setText(" ");
                Std_id.setText("");
            
            Stu_DOB.setDate(null);
            
            stu_image.setIcon(null);

            Pre_id.setText("");
           
            Pre_fname.setText("");
            Pre_Lname.setText("");
            Pre_nic.setText("");
            Pre_phone.setText("");
           
            
            
            
    }//GEN-LAST:event_Student_reset_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Student_btn;
    private javax.swing.JButton Delete_student_btn;
    private javax.swing.JTextField Pre_Lname;
    private javax.swing.JTextField Pre_fname;
    private javax.swing.JTextField Pre_id;
    private javax.swing.JTextField Pre_nic;
    private javax.swing.JTextField Pre_phone;
    private javax.swing.JTextArea Std_Address;
    private javax.swing.JTextField Std_id;
    private javax.swing.JTextField Std_phone;
    private com.toedter.calendar.JDateChooser Stu_DOB;
    private javax.swing.JTextField Stu_Lname;
    private javax.swing.JTextField Stu_Nic;
    private javax.swing.JTextField Stu_fname;
    private javax.swing.JTextField Stu_search_Id;
    private javax.swing.JButton Student_reset_btn;
    private javax.swing.JButton Student_search_btn;
    private javax.swing.JButton Update_student_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton img_chooser_btn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbt_Female;
    private javax.swing.JRadioButton rbt_Male;
    private javax.swing.JRadioButton rbt_pre_Female;
    private javax.swing.JRadioButton rbt_pre_male;
    private javax.swing.JLabel stu_image;
    // End of variables declaration//GEN-END:variables
byte[]student_img=null;
private ImageIcon format=null;

}
