/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_attendance_control_system;

import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author acer
 */
public class Teacher_Managment extends javax.swing.JFrame {

    /**
     * Creates new form Teacher_Managment
     */
    public Teacher_Managment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ID_search = new javax.swing.JTextField();
        Search_Teacher_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        teacher_fname = new javax.swing.JTextField();
        teacher_lname = new javax.swing.JTextField();
        teacher_subject = new javax.swing.JTextField();
        rbt_male = new javax.swing.JRadioButton();
        rbt_female = new javax.swing.JRadioButton();
        teacher_nic = new javax.swing.JTextField();
        teacher_DOB = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacher_address = new javax.swing.JTextArea();
        teacher_mobiNumber = new javax.swing.JTextField();
        Add_Teacher_btn = new javax.swing.JButton();
        Update_Teacher_btn = new javax.swing.JButton();
        Delete_Teacher_btn = new javax.swing.JButton();
        Reset_Teacher_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        teacher_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search Teacher"));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Teacher Id");

        Search_Teacher_btn.setBackground(new java.awt.Color(255, 255, 255));
        Search_Teacher_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Search_Teacher_btn.setForeground(new java.awt.Color(0, 0, 102));
        Search_Teacher_btn.setText("Search");
        Search_Teacher_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Teacher_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(ID_search, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Search_Teacher_btn)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addComponent(Search_Teacher_btn)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Manage Teacher"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("First name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Last name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Subject");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("NIC");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Date of Birth");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Address");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Mobile Number");

        buttonGroup1.add(rbt_male);
        rbt_male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbt_male.setForeground(new java.awt.Color(0, 0, 102));
        rbt_male.setText("Male");

        buttonGroup1.add(rbt_female);
        rbt_female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbt_female.setForeground(new java.awt.Color(0, 0, 102));
        rbt_female.setText("Female");

        teacher_address.setColumns(20);
        teacher_address.setRows(5);
        jScrollPane1.setViewportView(teacher_address);

        Add_Teacher_btn.setBackground(new java.awt.Color(255, 255, 255));
        Add_Teacher_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Add_Teacher_btn.setForeground(new java.awt.Color(0, 0, 102));
        Add_Teacher_btn.setText("Add");
        Add_Teacher_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Teacher_btnActionPerformed(evt);
            }
        });

        Update_Teacher_btn.setBackground(new java.awt.Color(255, 255, 255));
        Update_Teacher_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Update_Teacher_btn.setForeground(new java.awt.Color(0, 0, 102));
        Update_Teacher_btn.setText("update");
        Update_Teacher_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Teacher_btnActionPerformed(evt);
            }
        });

        Delete_Teacher_btn.setBackground(new java.awt.Color(255, 255, 255));
        Delete_Teacher_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Delete_Teacher_btn.setForeground(new java.awt.Color(0, 0, 102));
        Delete_Teacher_btn.setText("Delete");
        Delete_Teacher_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Teacher_btnActionPerformed(evt);
            }
        });

        Reset_Teacher_btn.setBackground(new java.awt.Color(255, 255, 255));
        Reset_Teacher_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reset_Teacher_btn.setForeground(new java.awt.Color(0, 0, 102));
        Reset_Teacher_btn.setText("Reset");
        Reset_Teacher_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_Teacher_btnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Teacher Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add_Teacher_btn)
                .addGap(18, 18, 18)
                .addComponent(Update_Teacher_btn)
                .addGap(18, 18, 18)
                .addComponent(Delete_Teacher_btn)
                .addGap(28, 28, 28)
                .addComponent(Reset_Teacher_btn)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(teacher_DOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teacher_mobiNumber)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(teacher_id, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(rbt_female))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbt_male)
                                    .addComponent(teacher_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacher_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacher_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacher_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(teacher_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(teacher_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(teacher_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbt_male)
                    .addComponent(rbt_female))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(teacher_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(teacher_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(teacher_mobiNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(teacher_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Teacher_btn)
                    .addComponent(Update_Teacher_btn)
                    .addComponent(Delete_Teacher_btn)
                    .addComponent(Reset_Teacher_btn))
                .addGap(23, 23, 23))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Manage Teacher");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_Teacher_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Teacher_btnActionPerformed
        String TID=teacher_id.getText();
        String TFirstName=teacher_fname.getText();
        String TLastName=teacher_lname.getText();
        String TNIC=teacher_nic.getText();
        char TGender=rbt_male.isSelected()?'M':'F';
        SimpleDateFormat date = new SimpleDateFormat("YYYY-MM-dd");
        String Date=date.format(teacher_DOB.getDate());
        

        String TPhoneNo=teacher_mobiNumber.getText();
        String TSubject=teacher_subject.getText();
        String TAddress=teacher_address.getText();

        ConnectionDB c = new ConnectionDB();

        try {
            //create statement
            Statement stmt=c.getConnectionDB().createStatement();
            //sql query
            String query = "insert into teacher (TeacherId,FName,LName,DOB,NIC,PhoneNo,Subject,TGender,Address)values('"+TID+"','"+ TFirstName+"','"+TLastName+"','"+Date+"','"+TNIC+"','"+TPhoneNo+"','"+TSubject+"','"+TGender+"','"+TAddress+"')";
            //execute query
            int n = stmt.executeUpdate(query);

            if(n!=0){
                JOptionPane.showMessageDialog(rootPane,"Record Successfully Added");

            }else {
                JOptionPane.showMessageDialog(rootPane," not record Successfully Added");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_Add_Teacher_btnActionPerformed

    private void Update_Teacher_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Teacher_btnActionPerformed
        
        String TID=teacher_id.getText();
        String TFirstName=teacher_fname.getText();
        String TLastName=teacher_lname.getText();
        String TNIC=teacher_nic.getText();
        char TGender=rbt_male.isSelected()?'M':'F';

        String TAddress=teacher_address.getText();
        String TPhoneNo=teacher_mobiNumber.getText();
        String TSubject=teacher_subject.getText();
        SimpleDateFormat date = new SimpleDateFormat("YYYY-MM-dd");
        String Date=date.format(teacher_DOB.getDate());

        ConnectionDB c=new ConnectionDB();
        try{
            //create statement
            Statement stmt=c.getConnectionDB().createStatement();
            //sql query
            String query="update teacher set TeacherId='"+TID+"',FName='"+TFirstName+"',LName='"+TLastName+"',NIC='"+TNIC+"',PhoneNo='"+TPhoneNo+"',Subject='"+TSubject+"',TGender='"+TGender+"',Address='"+TAddress+"',DOB='"+Date+"' where TeacherId='"+TID+"'";
            //execute query
            int n=stmt.executeUpdate(query);
            if(n!=0){
                JOptionPane.showMessageDialog(rootPane,"Updated Successfully");

            }
            else{
                JOptionPane.showMessageDialog(rootPane,"Update Wrong");
            }
            stmt.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_Update_Teacher_btnActionPerformed

    private void Delete_Teacher_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Teacher_btnActionPerformed
         String TeacherID=teacher_id.getText();
        ConnectionDB c=new ConnectionDB();

        try{
            
            Statement stmt=c.getConnectionDB().createStatement();
            
            String query="Delete from teacher where TeacherId='"+TeacherID+"'";
            
            int opt=JOptionPane.showConfirmDialog(rootPane,"Are you sure you want to delete this record?");
            System.out.println(opt);
            if(opt == 0){
                int n=stmt.executeUpdate(query);
                if(n!=0){
                    JOptionPane.showMessageDialog(rootPane,"Deleted Successfully");

                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"Error while deleting the record");

                }
            }
            else if(opt == 2){
                teacher_id.setText("");
                teacher_fname.setText("");
                teacher_lname.setText("");
                teacher_subject.setText("");
                buttonGroup1.clearSelection();
                teacher_nic.setText("");
                teacher_address.setText("");
                teacher_mobiNumber.setText("");
                ID_search.setText("");

                stmt.close();

            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
    }//GEN-LAST:event_Delete_Teacher_btnActionPerformed

    private void Search_Teacher_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Teacher_btnActionPerformed
      String ID=ID_search.getText();
        ConnectionDB c=new ConnectionDB();
        try{
            
            Statement stmt=c.getConnectionDB().createStatement();
           
            String query="select * from teacher where TeacherId='"+ID+"'";
            
            ResultSet rs=stmt.executeQuery(query);
            rs.next();
            teacher_id.setText(rs.getString("TeacherId"));
            teacher_fname.setText(rs.getString("FName"));
            teacher_lname.setText(rs.getString("LName"));
            
            Date date = new SimpleDateFormat("YYYY-MM-dd").parse((String)(rs.getString("DOB")));
            teacher_DOB.setDate(date);
            

            teacher_nic.setText(rs.getString("NIC"));
            teacher_subject.setText(rs.getString("Subject"));
            teacher_address.setText(rs.getString("Address"));
            teacher_mobiNumber.setText(rs.getString("PhoneNo"));

            if(rs.getString("TGender").equals("M"))
            {
                rbt_female.setSelected(false);
                rbt_male.setSelected(true);
              
            }
            else
            {
                System.out.println(""+rs.getString("TGender"));
                rbt_female.setSelected(true);
               
                rbt_male.setSelected(false);
               
            }
            teacher_address.setText(rs.getString("Address"));
            rs.close();
            stmt.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }                                         

    private void btnTSearchActionPerformed(java.awt.event.ActionEvent evt) {                                           
      
    }//GEN-LAST:event_Search_Teacher_btnActionPerformed

    private void Reset_Teacher_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_Teacher_btnActionPerformed
          teacher_id.setText("");
        teacher_fname.setText("");
        teacher_lname.setText("");
        teacher_subject.setText("");
        buttonGroup1.clearSelection();
        teacher_nic.setText("");
        teacher_address.setText("");
        teacher_mobiNumber.setText("");
        ID_search.setText("");
        teacher_DOB.setDate(null);
    }//GEN-LAST:event_Reset_Teacher_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_Managment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Teacher_btn;
    private javax.swing.JButton Delete_Teacher_btn;
    private javax.swing.JTextField ID_search;
    private javax.swing.JButton Reset_Teacher_btn;
    private javax.swing.JButton Search_Teacher_btn;
    private javax.swing.JButton Update_Teacher_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton rbt_female;
    private javax.swing.JRadioButton rbt_male;
    private com.toedter.calendar.JDateChooser teacher_DOB;
    private javax.swing.JTextArea teacher_address;
    private javax.swing.JTextField teacher_fname;
    private javax.swing.JTextField teacher_id;
    private javax.swing.JTextField teacher_lname;
    private javax.swing.JTextField teacher_mobiNumber;
    private javax.swing.JTextField teacher_nic;
    private javax.swing.JTextField teacher_subject;
    // End of variables declaration//GEN-END:variables
}
