/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_attendance_control_system;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class UserProfile_Managment extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile_Managment
     */
    public UserProfile_Managment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        searchUsername = new javax.swing.JTextField();
        User_Search_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FName = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        PhoneNo = new javax.swing.JTextField();
        UNIC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        UAddress = new javax.swing.JTextArea();
        rbnAdmin = new javax.swing.JRadioButton();
        rbnStaff = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Eusername = new javax.swing.JTextField();
        User_Add_btn = new javax.swing.JButton();
        User_Update_btn = new javax.swing.JButton();
        User_Delete_btn = new javax.swing.JButton();
        Use_Reset_btn = new javax.swing.JButton();
        rbnUMale = new javax.swing.JRadioButton();
        rbnUFemale = new javax.swing.JRadioButton();
        UPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search User"));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("User name");

        User_Search_btn.setBackground(new java.awt.Color(255, 255, 255));
        User_Search_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        User_Search_btn.setForeground(new java.awt.Color(0, 0, 102));
        User_Search_btn.setText("Search");
        User_Search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_Search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(User_Search_btn)
                    .addComponent(searchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(266, 266, 266))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(searchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(User_Search_btn)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "User Managment"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("User type");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("First name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Last name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Mobile Number");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("NIC");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Address");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Gender");

        UAddress.setColumns(20);
        UAddress.setRows(5);
        jScrollPane1.setViewportView(UAddress);

        buttonGroup1.add(rbnAdmin);
        rbnAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbnAdmin.setForeground(new java.awt.Color(0, 0, 102));
        rbnAdmin.setText("Admin");

        buttonGroup1.add(rbnStaff);
        rbnStaff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbnStaff.setForeground(new java.awt.Color(0, 0, 102));
        rbnStaff.setText("staff");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("User name");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Password");

        Eusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EusernameActionPerformed(evt);
            }
        });

        User_Add_btn.setBackground(new java.awt.Color(255, 255, 255));
        User_Add_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        User_Add_btn.setForeground(new java.awt.Color(0, 0, 102));
        User_Add_btn.setText("Add");
        User_Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_Add_btnActionPerformed(evt);
            }
        });

        User_Update_btn.setBackground(new java.awt.Color(255, 255, 255));
        User_Update_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        User_Update_btn.setForeground(new java.awt.Color(0, 0, 102));
        User_Update_btn.setText("Update");
        User_Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_Update_btnActionPerformed(evt);
            }
        });

        User_Delete_btn.setBackground(new java.awt.Color(255, 255, 255));
        User_Delete_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        User_Delete_btn.setForeground(new java.awt.Color(0, 0, 102));
        User_Delete_btn.setText("Delete");
        User_Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_Delete_btnActionPerformed(evt);
            }
        });

        Use_Reset_btn.setBackground(new java.awt.Color(255, 255, 255));
        Use_Reset_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Use_Reset_btn.setForeground(new java.awt.Color(0, 0, 102));
        Use_Reset_btn.setText("Reset");
        Use_Reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Use_Reset_btnActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbnUMale);
        rbnUMale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbnUMale.setForeground(new java.awt.Color(0, 0, 102));
        rbnUMale.setText("Male");

        buttonGroup2.add(rbnUFemale);
        rbnUFemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbnUFemale.setForeground(new java.awt.Color(0, 0, 102));
        rbnUFemale.setText("Female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FName)
                                    .addComponent(LName)
                                    .addComponent(UNIC)
                                    .addComponent(PhoneNo)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbnAdmin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rbnStaff))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbnUMale)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rbnUFemale)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Eusername, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(UPassword))))
                        .addGap(80, 80, 80))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(User_Add_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(User_Update_btn)
                        .addGap(18, 18, 18)
                        .addComponent(User_Delete_btn)
                        .addGap(18, 18, 18)
                        .addComponent(Use_Reset_btn)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbnAdmin)
                    .addComponent(rbnStaff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(UNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbnUMale)
                        .addComponent(rbnUFemale)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Eusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(UPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_Add_btn)
                    .addComponent(User_Update_btn)
                    .addComponent(User_Delete_btn)
                    .addComponent(Use_Reset_btn))
                .addGap(28, 28, 28))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Manage User");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EusernameActionPerformed

    private void User_Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_Add_btnActionPerformed
 try {
            char Usertype = rbnStaff.isSelected()?'S':'A';
            String Firstname = FName.getText();
            String Lastname = LName.getText();
            String TelephoneNo = PhoneNo.getText();
            String NIC = UNIC.getText();
            String Address =UAddress.getText();
            char Gender = rbnUMale.isSelected()?'M':'F';
            String username = Eusername.getText();
            String Password = UPassword.getText();
           // String aes=AESencrp.encrypt(Password);
           // System.out.println("password : "+aes);
            ConnectionDB c = new ConnectionDB();

            try {
                //create statement
                Statement stmt=c.getConnectionDB().createStatement();
                //sql query
                String query1 = "insert into employee (FName,LName,EmpType,Address,Password,PhoneNo,Gender,NIC,UserName)values('"+ Firstname+"','"+Lastname+"','"+Usertype+"','"+Address+"','"+Password+"','"+TelephoneNo+"','"+Gender+"','"+NIC+"','"+username+"')";
                //execute query
                
                   int n1=stmt.executeUpdate(query1,Statement.RETURN_GENERATED_KEYS);
            if(n1!=0){
                ResultSet rs=stmt.getGeneratedKeys();
                rs.next();

                //sql query2
                String query2="insert into login(UserName,UserType,PPassword) values('"+username+"','"+Usertype+"','"+Password+"')";
                int n2=stmt.executeUpdate(query2);
                if(n2!=0){
                    JOptionPane.showMessageDialog(rootPane,"Registration successful");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"Registration not successful");
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"Error while inserting records");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        
        
        
               
    }//GEN-LAST:event_User_Add_btnActionPerformed

    private void User_Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_Update_btnActionPerformed
 char Usertype = rbnStaff.isSelected()?'S':'A';
        String Firstname = FName.getText();
        String Lastname = LName.getText();
        String TelephoneNo = PhoneNo.getText();
        String NIC = UNIC.getText();
        String Address = UAddress.getText();
        char Gender = rbnUMale.isSelected()?'M':'F';
        String uusername = Eusername.getText();
        String searchu=searchUsername.getText();
        String Password = UPassword.getText();
      

        ConnectionDB c = new ConnectionDB();
        try{
            //create statement
            Statement stmt=c.getConnectionDB().createStatement();
            //sql query
            String query = " Update employee set FName = '"+Firstname+"',LName='"+Lastname +"',EmpType='"+Usertype+"',Address ='"+Address+"',Password='"+Password+"',PhoneNo='"+TelephoneNo+"',Gender ='"+Gender+"',NIC='"+NIC+"',UserName='"+uusername+"' where UserName= '"+searchu+"' ";
            String query2 = " Update login set UserName = '"+uusername+"',UserType='"+Usertype +"',PPassword='"+Password+"' where UserName= '"+searchu+"' ";

//execute query
            int n =  stmt.executeUpdate(query);
             int n1 =  stmt.executeUpdate(query2);
            if(n!=0){
                JOptionPane.showMessageDialog(rootPane,"Update Successfully");
            }else {
                JOptionPane.showMessageDialog(rootPane,"Update Wrong");
            }
            stmt.close();

        }  catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_User_Update_btnActionPerformed

    private void User_Search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_Search_btnActionPerformed
        // TODO add your handling code here:
         String susername =searchUsername.getText();
        //  String Password = String.valueOf(jPasswordField1.getPassword());

        ConnectionDB c = new ConnectionDB();

        try{
            //create statement
            Statement stmt=c.getConnectionDB().createStatement();
            //sql query
            String query = "Select * from employee where UserName ='"+susername+"'";
            //execute query
            ResultSet rs = stmt.executeQuery(query);
            rs.next();

            FName.setText(rs.getString("FName"));
            LName.setText(rs.getString("LName"));
            UAddress.setText(rs.getString("Address"));
            UPassword.setText(rs.getString("Password"));
            Eusername.setText(rs.getString("UserName"));
            PhoneNo.setText(rs.getString("PhoneNo"));
            UNIC.setText(rs.getString("NIC"));

            if(rs.getString("Gender").equals("M"))
            {
                rbnUFemale.setSelected(false);
                rbnUFemale.setSelected(false);
                rbnUMale.setSelected(true);
                // rbnPMale.setSelected(true);
            }
            else
            {
                System.out.println(""+rs.getString("Gender"));
                rbnUFemale.setSelected(true);
                rbnUFemale.setSelected(true);
                rbnUMale.setSelected(false);
                //  rbnPMale.setSelected(false);
            }
            if(rs.getString("EmpType").equals("S"))
            {
                rbnAdmin.setSelected(false);
                rbnAdmin.setSelected(false);
                rbnStaff.setSelected(true);
                // rbnPMale.setSelected(true);
            }
            else
            {
                System.out.println(""+rs.getString("EmpType"));
                rbnAdmin.setSelected(true);
                rbnAdmin.setSelected(true);
                rbnStaff.setSelected(false);
                //  rbnPMale.setSelected(false);
            }

            rs.close();
            stmt.close();

        }  catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_User_Search_btnActionPerformed

    private void User_Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_Delete_btnActionPerformed
        // TODO add your handling code here:
          String deleteusername = searchUsername.getText();

        ConnectionDB c=new ConnectionDB();
        try {

            //create statement
            Statement stmt = c.getConnectionDB().createStatement();
            //sql query
            String query = "Delete from employee where UserName = '"+deleteusername+"'";
             String query1 = "Delete from login where UserName = '"+deleteusername+"'";
            //execute query
            int opt = JOptionPane.showConfirmDialog(rootPane,"Are you sure you want to delete this record?");
            System.out.println(opt);
            if(opt == 0){
                int n = stmt.executeUpdate(query);
               int n1 = stmt.executeUpdate(query1);
                if(n!=0){
                    JOptionPane.showMessageDialog(rootPane,"Deleted successfully");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"Error while deleting the record");
                }

            }
            else if(opt == 2){
                buttonGroup1.clearSelection();
                FName.setText("");
                LName.setText("");
                UNIC.setText("");
                PhoneNo.setText("");
                UAddress.setText("");
                buttonGroup2.clearSelection();
                UPassword.setText("");
                Eusername.setText("");
                
            }
            stmt.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
    }//GEN-LAST:event_User_Delete_btnActionPerformed

    private void Use_Reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Use_Reset_btnActionPerformed
        // TODO add your handling code here:
         buttonGroup1.clearSelection();
        FName.setText("");
        LName.setText("");
        PhoneNo.setText("");
        UNIC.setText("");
        UAddress.setText("");
        buttonGroup2.clearSelection();
        Eusername.setText("");
        UPassword.setText("");
        searchUsername.setText("");
    }//GEN-LAST:event_Use_Reset_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile_Managment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Eusername;
    private javax.swing.JTextField FName;
    private javax.swing.JTextField LName;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JTextArea UAddress;
    private javax.swing.JTextField UNIC;
    private javax.swing.JPasswordField UPassword;
    private javax.swing.JButton Use_Reset_btn;
    private javax.swing.JButton User_Add_btn;
    private javax.swing.JButton User_Delete_btn;
    private javax.swing.JButton User_Search_btn;
    private javax.swing.JButton User_Update_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbnAdmin;
    private javax.swing.JRadioButton rbnStaff;
    private javax.swing.JRadioButton rbnUFemale;
    private javax.swing.JRadioButton rbnUMale;
    private javax.swing.JTextField searchUsername;
    // End of variables declaration//GEN-END:variables
}
